#!/bin/sh

userresources=$XDG_CONFIG_HOME/X11/xresources

# try to start docked.
# if no monitor is connected this command returns 1
external-monitor dock

# merge in defaults and keymaps

if [ -f "$userresources" ]; then
	xrdb -merge "$userresources"
fi

# start some nice programs

export QT_QPA_PLATFORMTHEME=qt5ct
eval $(gnome-keyring-daemon --start --components=secrets,ssh)
export SSH_AUTH_SOCK

udiskie --smart-tray &
exec i3
