#!/bin/sh

userresources=$XDG_CONFIG_HOME/X11/xresources

# merge in defaults and keymaps

if [ -f "$userresources" ]; then
	xrdb -merge "$userresources"
fi

# don't turn off the screen/monitor power
xset s off -dpms

# start some nice programs

# detect current monitor setup
autorandr --change

export QT_QPA_PLATFORMTHEME=qt5ct
eval $(gnome-keyring-daemon --start --components=secrets,ssh)
export SSH_AUTH_SOCK

udiskie --smart-tray &
exec i3
