#!/bin/zsh

# colorls
#alias ls='colorls'

# Neovim
#alias vi='nvim'
#alias vim='nvim'

# Lynx
alias lynx='lynx -vikeys -accept_all_cookies'

# wget
alias wget="wget --hsts-file $XDG_CACHE_HOME/.wget-hsts"
