#!/bin/zsh

# cp
alias cp='cp -iv'
alias mv='mv -iv'
alias rm='rm -iv'

# dotfiles
alias dots='cd $DOTFILES'

# grep
alias grep='grep --color=auto'

# ls
if [ -x $(command -v "colorls") ]; then
    alias ls='colorls --group-directories-first'
else
    alias ls='ls --color=auto --group-directories-first'
fi
alias ll='ls -gho'
alias lall='ls -ghoA'

# Lynx
alias lynx='lynx -vikeys -accept_all_cookies'

# Neovim
alias vi='vim'
[ -x "$(command -v nvim)" ] && alias vim="nvim"

# sudo
alias sudo="nocorrect sudo "

# wget
alias wget="wget --hsts-file $XDG_CACHE_HOME/.wget-hsts"
