#!/bin/zsh

# cp
alias cp='cp -iv'
alias mv='mv -iv'

# ls
if [ -x $(command -v "colorls") ]; then
    alias ls='colorls --group-directories-first'
else
    alias ls='ls --color=auto --group-directories-first'
fi
alias lall='ls -ghoA'

# grep
alias grep='grep --color=auto'

# Neovim
alias vi='vim'
[ -x "$(command -v nvim)" ] && alias vim="nvim"

# Lynx
alias lynx='lynx -vikeys -accept_all_cookies'

# wget
alias wget="wget --hsts-file $XDG_CACHE_HOME/.wget-hsts"
