#!/bin/zsh

# Environment variables

# X
export XAUTHORITY=/tmp/xauthority

# XDG
export XDG_CONFIG_HOME=$HOME/.config
export XDG_DATA_HOME=$XDG_CONFIG_HOME/local/share
export XDG_CACHE_HOME=$XDG_CONFIG_HOME/cache

# editor
export EDITOR="nvim"
export VISUAL="nvim"

# zsh
export ZDOTDIR="$XDG_CONFIG_HOME/zsh"
export HISTFILE="$ZDOTDIR/.zshitory"
export HISTSIZE=1000
export SAVEHIST=1000

# rust
export CARGO_HOME=$XDG_DATA_HOME/.cargo

