#!/bin/zsh

# options
setopt autocd
setopt extendedglob
unsetopt beep

# keybindings
bindkey -v

# completion
zstyle ':completion:*' completer _complete _ignored _approximate
zstyle ':completion:*' list-colors ${(s.:.)LS_COLORS}
zstyle ':completion:*' max-errors 2
zstyle ':completion:*' prompt 'Corrected %e errors'

autoload -Uz compinit; compinit

# prompt 
fpath=($DOTFILES/zsh/prompt $fpath)
autoload -U promptinit; promptinit
zstyle :prompt:pure:prompt:success color green
prompt pure

# startup
if [ -z "${DISPLAY}" ] && [ "${XDG_VTNR}" -eq 1 ]; then
    exec startx "$XDG_CONFIG_HOME/X11/xinitrc"
fi

